import Providers from "@/components/Providers";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthProvider from "./context/AuthProvider";
import { ChakraProvider } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
        <AuthProvider>
          <meta name="viewport" content="initial-scale=1, width=device-width" />
          <body className={inter.className}>
            <Providers>{children}</Providers>
          </body>
        </AuthProvider>
    </html>
  );
}
